@startuml
'https://plantuml.com/sequence-diagram
class Human{
    -Mood mood;
    -Gender gender;
    +say
    +shareMood
    +changeMood
}
abstract class Animal
abstract class Creature{
    -int health
    -int stamina
    -int hunger
    -int age
    -int power
    -Location previousLocation
    -Location location
    -ArrayList<SuperProperty> properties
    +downPower()
    +upPower()
    +toHunger()
    +eat()
    +downStamina()
    +upStamina()
    +takeDamage()
    +takeTreatment()
    +plusAge()
}
class HumanWithPropeller{
    -int amountOfJam
    +flyUp()
    +flyTo()
    +refuelJam()
    +wasteJam()
}
abstract class Item
abstract class Entity{
    #String name
}
enum Gender
enum Location
enum Mood
enum InProperty
enum OutProperty

Interface Locationable{
    void changeLocation
    void comeBack
}
Interface Entityable{
    getTypeName();
    getName();
}
Interface Propertyable{
    cleanProperties()
    updateProperties()
    removeProperties()
    addProperties()
}
Interface SuperProperty

Gender *-- Creature
Location *-- Creature
Mood *--- Human
InProperty *-- Creature
InProperty *-- Item
OutProperty *-- Creature
OutProperty *-- Item

Entityable <|.. Entity
Locationable <|.. Creature
Propertyable <|... Item
Locationable <|... Item
SuperProperty <|..InProperty
SuperProperty <|..OutProperty
Propertyable <|.. Creature

Entity <|-- Creature
Creature <|-- Human
Creature <|-- Animal
Human <|-- HumanWithPropeller
Entity <|-- Item

@enduml